---
version: '3.5'
services:
  hugo:
    container_name: recipes
    build: .
    volumes:
      - ./hugo:/app
      - ./scrape.py:/scrape.py
    ports:
      - "1313:1313"
    command: hugo server --bind=0.0.0.0 --disableFastRender
    networks:
      - web
networks:
  web:
